model_list:
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama_chat/tinyllama
    tool_choice: none
  model_name: tinyllama
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama/nomic-embed-text
    tool_choice: none
  model_name: nomic-embed-text
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama_chat/bge-m3
    tool_choice: none
  model_name: bge-m3
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama/embeddinggemma
    tool_choice: none
  model_name: embeddinggemma
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama/mxbai-embed-large
    tool_choice: none
  model_name: mxbai-embed-large
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama/nomic-embed-text:latest
    tool_choice: none
  model_name: nomic-embed-text:latest
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama_chat/gpt-oss:20b
    tool_choice: none
  model_name: gpt-oss:20b
- litellm_params:
    api_base: http://nodegpu102:11055
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama_chat/gemma4
    tool_choice: none
  model_name: gemma4
- litellm_params:
    api_base: http://nodegpu106:20978
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: ollama_chat/juilpark/gemma-4-31B-it-uncensored-heretic:q4_k_m
    tool_choice: none
  model_name: juilpark/gemma-4-31B-it-uncensored-heretic:q4_k_m
- litellm_params:
    api_base: http://nodegpu106:20978
    api_key: dummy-key
    ctx_size: 8192
    drop_params: true
    extra_body:
      options:
        num_ctx: 16384
    max_parallel_requests: 20
    model: ollama_chat/tinyrick/gemma-4-31B-it-uncensored-heretic-vision-llmfan46:Q4_K_M
    num_ctx: 256000
    tool_choice: none
  model_name: tinyrick/gemma-4-31B-it-uncensored-heretic-vision-llmfan46:Q4_K_M
- litellm_params:
    api_base: http://nodegpu105:20582/v1
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: openai/flux.1-dev
    tool_choice: none
  model_info:
    mode: image_generation
  model_name: flux.1-dev
- litellm_params:
    api_base: http://nodegpu105:20582/v1
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: openai/Z-Image-Turbo
    tool_choice: none
  model_info:
    mode: image_generation
  model_name: Z-Image-Turbo
- litellm_params:
    api_base: http://nodegpu105:20582/v1
    api_key: dummy-key
    drop_params: true
    max_parallel_requests: 5
    model: openai/versatillama-llama-3.2-3b-instruct-abliterated
    tool_choice: none
  model_info:
    mode: image_generation
  model_name: versatillama-llama-3.2-3b-instruct-abliterated
