#!/bin/bash
#SBATCH -c 4
#SBATCH --mem 4G
#SBATCH -p shortq7

trap 'pkill -P $$' EXIT
# Change dir to scripts location
cd "$(dirname "$0")" || exit

# Load python 3.12, you must update this to match your modules or python install
# Technically venv should hand this but, it has been a long night
# and this makes it work for the author
echo Loading pyrhon
module load python/3.12.4-gcc-13.2.0-ryucfix

echo Checking for venv
if [ ! -d .venv ]
then
	echo Creating venv
	python -m venv .venv
        source .venv/bin/activate
	# Check Requirements are up to date
        echo Checking requirements.txt
	pip install -r requirements.txt
	deactivate
fi

echo Activating venv
source .venv/bin/activate


# Echo Starting proxy
# Logging is a bit verbose (thanks gemini)
if [ "$SLURM_JOB_ID" == "" ]
then
	export SLURM_JOB_ID=1000
fi

PORT=$((11000 + ($SLURM_JOB_ID % 10000)))

python proxy.py --port=$PORT > logs/proxy.log 2>&1 &

echo Starting auto ssh
if [ "$AUTO_SSH" == "true" ]
then
autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -N  xantho@home.scuba2deth.com -R 11434:0.0.0.0:$PORT
fi

wait
