model_list:
- litellm_params:
    api_base: http://nodegpu106:20094
    model: ollama/tinyrick/gemma-4-31B-it-uncensored-heretic-vision-llmfan46:Q4_K_M
  model_name: tinyrick/gemma-4-31B-it-uncensored-heretic-vision-llmfan46:Q4_K_M
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/tinyllama
  model_name: tinyllama
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/nomic-embed-text
  model_name: nomic-embed-text
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/bge-m3
  model_name: bge-m3
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/embeddinggemma
  model_name: embeddinggemma
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/mxbai-embed-large
  model_name: mxbai-embed-large
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/nomic-embed-text:latest
  model_name: nomic-embed-text:latest
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/text-embedding-3-small
  model_name: text-embedding-3-small
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/text-embedding-3-large
  model_name: text-embedding-3-large
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/BAAI/bge-large-en-v1.5
  model_name: BAAI/bge-large-en-v1.5
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/sentence-transformers/all-mpnet-base-v2
  model_name: sentence-transformers/all-mpnet-base-v2
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/HammerAI/gemma-4-e4b-heretic
  model_name: HammerAI/gemma-4-e4b-heretic
- litellm_params:
    api_base: http://nodegpu107:20095
    model: ollama/llama3.3
  model_name: llama3.3
