#models:
#  llama3:
#    max_wait_time_sec: 5.0
#    sbatch_command: "sbatch run_llama3.sh"
# mistral:
#    max_wait_time_sec: 10.0
#    sbatch_command: "sbatch run_mistral.sh"
#
jobs:
  - job_name: "bulk-llm"
    models:
      - tinyllama
      - nomic-embed-text 
      - bge-m3 
      - embeddinggemma
      - mxbai-embed-large 
      - nomic-embed-text:latest
      - HammerAI/gemma-4-e4b-heretic
      - llama3.2
      - llama3.1
  - job_name: "big-gemma"
    models:
      - tinyrick/gemma-4-31B-it-uncensored-heretic-vision-llmfan46:Q4_K_M
  - job_name: "big-llama3.3"
    models:
      - llama3.3
      - huihui_ai/llama3.3-abliterated:latest
