#!/bin/bash


# Store the recommended embedding models in an array
RECOMMENDED_EMBEDS=(
  "nomic-embed-text"
  "bge-m3"
  "mxbai-embed-large"
  "text-embedding-3-small"
  "text-embedding-3-large"
  "BAAI/bge-large-en-v1.5"
  "sentence-transformers/all-mpnet-base-v2"
)

sbatch --comment="$RECOMMENDED_EMBEDS"  sbatch.sh
sbatch --comment=gemma4:e4b sbatch.sh
sbatch --comment=llama3.3 sbatch.sh
sbatch --comment=gemma4:31b sbatch.sh

